/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsAndConditionsRouteImport } from './routes/terms-and-conditions'
import { Route as SummitRouteImport } from './routes/summit'
import { Route as SpeakersRouteImport } from './routes/speakers'
import { Route as ReturnPolicyRouteImport } from './routes/return-policy'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as PartnersRouteImport } from './routes/partners'
import { Route as AttendRouteImport } from './routes/attend'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const TermsAndConditionsRoute = TermsAndConditionsRouteImport.update({
  id: '/terms-and-conditions',
  path: '/terms-and-conditions',
  getParentRoute: () => rootRouteImport,
} as any)
const SummitRoute = SummitRouteImport.update({
  id: '/summit',
  path: '/summit',
  getParentRoute: () => rootRouteImport,
} as any)
const SpeakersRoute = SpeakersRouteImport.update({
  id: '/speakers',
  path: '/speakers',
  getParentRoute: () => rootRouteImport,
} as any)
const ReturnPolicyRoute = ReturnPolicyRouteImport.update({
  id: '/return-policy',
  path: '/return-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersRoute = PartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const AttendRoute = AttendRouteImport.update({
  id: '/attend',
  path: '/attend',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/attend': typeof AttendRoute
  '/partners': typeof PartnersRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/return-policy': typeof ReturnPolicyRoute
  '/speakers': typeof SpeakersRoute
  '/summit': typeof SummitRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/attend': typeof AttendRoute
  '/partners': typeof PartnersRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/return-policy': typeof ReturnPolicyRoute
  '/speakers': typeof SpeakersRoute
  '/summit': typeof SummitRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/attend': typeof AttendRoute
  '/partners': typeof PartnersRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/return-policy': typeof ReturnPolicyRoute
  '/speakers': typeof SpeakersRoute
  '/summit': typeof SummitRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/attend'
    | '/partners'
    | '/privacy-policy'
    | '/return-policy'
    | '/speakers'
    | '/summit'
    | '/terms-and-conditions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/attend'
    | '/partners'
    | '/privacy-policy'
    | '/return-policy'
    | '/speakers'
    | '/summit'
    | '/terms-and-conditions'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/attend'
    | '/partners'
    | '/privacy-policy'
    | '/return-policy'
    | '/speakers'
    | '/summit'
    | '/terms-and-conditions'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AttendRoute: typeof AttendRoute
  PartnersRoute: typeof PartnersRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  ReturnPolicyRoute: typeof ReturnPolicyRoute
  SpeakersRoute: typeof SpeakersRoute
  SummitRoute: typeof SummitRoute
  TermsAndConditionsRoute: typeof TermsAndConditionsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms-and-conditions': {
      id: '/terms-and-conditions'
      path: '/terms-and-conditions'
      fullPath: '/terms-and-conditions'
      preLoaderRoute: typeof TermsAndConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/summit': {
      id: '/summit'
      path: '/summit'
      fullPath: '/summit'
      preLoaderRoute: typeof SummitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/speakers': {
      id: '/speakers'
      path: '/speakers'
      fullPath: '/speakers'
      preLoaderRoute: typeof SpeakersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/return-policy': {
      id: '/return-policy'
      path: '/return-policy'
      fullPath: '/return-policy'
      preLoaderRoute: typeof ReturnPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attend': {
      id: '/attend'
      path: '/attend'
      fullPath: '/attend'
      preLoaderRoute: typeof AttendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AttendRoute: AttendRoute,
  PartnersRoute: PartnersRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  ReturnPolicyRoute: ReturnPolicyRoute,
  SpeakersRoute: SpeakersRoute,
  SummitRoute: SummitRoute,
  TermsAndConditionsRoute: TermsAndConditionsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
